app: soccer-it
tenant: mjunior
service: soccer-it-crawling-scraping

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 2536
  timeout: 180
  region: sa-east-1
  stage: ${opt:stage, 'dev'}

functions:
  campeonatoBrasileiroScraperFunc:
    handler: robot/index.handler
    events:
      - http:
          path: scrapers/
          method: get

package:
  exclude:
    - .vscode/**
    - .editorconfig
    - .prettierrc.json
    - .prettierignore
    - .env
    - .gitignore
    - Dockerfile
    - README.MD
    - "*.{ts,js,json,yml}"
    - node_modules/puppeteer/.local-chromium/**

  include:
    - app/**
    - config.js
    - robot/index.js

plugins:
  - serverless-offline
  - serverless-plugin-chrome

chrome:
  flags:
    - --window-size=1280,1696
    - --hide-scrollbars
    - --ignore-certificate-errors
