[package]
name = "championships-carioca"
version = "0.1.0"
authors = ["Victor Igor <victor.0w3@gmail.com>"]
edition = "2018"

[dependencies]
select = "0.4.2"
reqwest = "0.9.6"
regex = "1"
itertools = "0.8.0"